name: A sample workflow

on: push

jobs:
    job_1:
      runs-on: ubuntu-latest
      steps:
      - name : Checkout Repo
        uses: actions/checkout@v4 
      - name : List and read files
        run: |
          echo "First GitHub Actions Job"
          ls -lrta
          cat README.md
      - name : Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover I am a dragon...." >> dragon.txt

      #- name: List files
      #  run: ls

      #- name: Read the file
      #  run: cat README.md


