name: Generate ASCII Art Work

on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name : Checkout Repo
        uses: actions/checkout@v4  
      - name : List files in Repo
        run: ls -ltra
      - name : Executing Shell Script
        run: |
             chmod x ascii_script.sh
             ./ascii_script.sh      
