name: A Multi Job Example

on: push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay cmd
        run: cowsay -f dragon "Err... I am a Dragon emitting fire !!" >> dragon.txt
      - name: Upload dragan file
        uses: actions/upload-artifact@v4
        with:
         name: dragon-text-file
         path: dragon.txt

    test_job:
     runs-on: ubuntu-latest
     needs: build_job
     steps:
     - name: download dragan file
       uses: actions/download-artifact@v4
       with:
          name: dragon-text-file
     - name: Test file exists
       run: grep -i "dragon" dragon.txt

    deploy_job:
     runs-on: ubuntu-latest
     needs: [test_job]
     steps:
     - name: download dragan file
       uses: actions/download-artifact@v4
       with:
         name: dragon-text-file
     - name: reading file
       run: cat dragon.txt
     - name: deploying
       run: echo "deploying ...."

      
   